# -*- mode: ruby -*-
# vi: set ft=ruby :

require '../../common/common.rb'

Common.configure('precise64') do |config|
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision :shell, :inline => "/platform/linux/bootstrap.sh"
end
