# -*- mode: ruby -*-
# vi: set ft=ruby :

require '../../common/common.rb'
externs = Common::Externs.new 'precise64'

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision :shell, :inline => "/platform/linux/bootstrap.sh"
  externs.add_common_configs config
end
