# -*- mode: ruby -*-
# vi: set ft=ruby :

require '../../common/common.rb'

Common.configure('win7-32') do |config, externs|
  config.vm.guest = :windows
  config.vm.box_url = (externs.local_box_path "win7-32.box")

  config.windows.halt_timeout = 25
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985
end
