# -*- mode: ruby -*-
# vi: set ft=ruby :

require '../../common/common.rb'

Common.configure('precise32') do |config, externs|
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.provision :shell, :inline => "/platform/linux/bootstrap.sh"
end
